name = "Perl-Lint"
badges = ["travis", "coveralls"]
authority="cpan:MOZNION"
module_maker="ModuleBuildTiny"

[release]
hooks = [
    "perl t/Policy/Variables/require_localized_punctuation_vars.PL",
    "perl t/Policy/ControlStructures/prohibit_negative_expressions_in_unless_and_until_conditions.PL",
    "perl t/Policy/NamingConventions/capitalization.PL"
]

